
name: Flutter APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'

      - name: Build Complete Fresh Project
        run: |
          cd ..
          flutter create --org com.harsh.alya alya_project --platforms android
          cd alya_project
          
          # Hamaari custom files copy kar rahe hain
          cp -f $GITHUB_WORKSPACE/pubspec.yaml ./pubspec.yaml
          cp -f $GITHUB_WORKSPACE/lib/main.dart ./lib/main.dart
          
          # Dependencies install aur APK build isi folder mein hoga
          flutter pub get
          flutter build apk --release --no-tree-shake-icons
          
          # Build khatam hone ke baad APK ko wapas sahi jagah bhej rahe hain
          mkdir -p $GITHUB_WORKSPACE/build/app/outputs/flutter-apk/
          cp build/app/outputs/flutter-apk/app-release.apk $GITHUB_WORKSPACE/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

